FROM ubuntu:12.04

MAINTAINER Tillson Galloway

RUN apt-get update && apt-get install -y apache2 && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

EXPOSE 80

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]

RUN apt-get update && apt-get install -y php5 libapache2-mod-php5 php5-mysql php5-cli && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY server /var/www
WORKDIR /var/www
RUN rm /var/www/index.html

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
